elems:

  - src:   ^(xsessions)/(.+\.desktop)$
    dst:   /usr/share/<1>/<2>
    perms: 755
    only:  f?xorg

  - src:   ^xsessions/((?!.*\.desktop).+)$
    dst:   /etc/X11/Sessions/<1>
    perms: 755
    only:  f?xorg

  - src:  '^xsessions/<%= get_var! :"xorg.default_session" %>$'
    dst:  /etc/X11/xinit/xinitrc
    only: f?xorg && v?xorg.default_session

  - src: ^xresources/main$
    dst: '<%= get_var! :"xorg.xresources.main" %>'
    only: f?xorg

  - src: ^xresources/colorschemes/(.+)$
    dst: '<%= get_var! :"xorg.xresources.custom_dir", type: :directory %>/colorschemes/<1>'
    only: f?xorg

  - src: ^(xorg\.conf\.d/[0-9]+-apple\.conf)$
    dst: /etc/X11/<1>
    only: f?xorg && f?macbook

  - src: ^(xorg\.conf\.d/[0-9]+-wacom\.conf)$
    dst: /etc/X11/<1>
    only: f?xorg && f?wacom

  - src: ^(xorg\.conf\.d/20-video-card\.conf)$
    dst: /etc/X11/<1>
    only: f?xorg && v?xorg.main_video_card


# vim: set filetype=eruby.yaml :
